language: node_js

node_js:
  - '0.11'
  - '0.10'

after_script:
  - cat ./coverage/coverage.json | ./node_modules/coveralls/bin/coveralls.js
  - cat ./coverage/coverage.json | ./node_modules/codeclimate-test-reporter/bin/codeclimate.js